# Generated by Django 2.1.7 on 2019-04-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageTables', '0002_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetables',
            name='ACCESS',
            field=models.CharField(default='0', max_length=8),
            preserve_default=False,
        ),
    ]
