# Generated by Django 2.1.7 on 2019-04-30 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manageTables', '0003_activetables_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers', models.CharField(max_length=200)),
                ('items', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('time_seated', models.IntegerField(default=0)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageTables.Server')),
            ],
        ),
    ]
